name: "Tests"
description: "Run brownie fork tests"

inputs:
  vote:
    description: "vote type: normal or large"
    required: false
    default: "normal"
  rpc_url:
    description: "Ethereum RPC URL (any provider: Infura, Alchemy, custom)"
    required: true
    default: ""
  etherscan:
    description: "etherscan api key"
    required: true
    default: ""
  command:
    description: "command to execute tests"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      env:
        POETRY_VERSION: "1.8.2"

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: poetry

    - name: Setup node.js version
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: "yarn"

    - name: Install poetry requirements
      shell: bash
      run: poetry install

    - name: Install ganache
      shell: bash
      run: yarn install --frozen-lockfile

    - name: Import network config to connect brownie with local Ganache
      shell: bash
      run: poetry run brownie networks import network-config.yaml True

    - name: Show system info
      shell: bash
      run: |
        echo "Memory and swap:"
        free -h
        echo
        swapon --show
        echo
        df -h
        echo
        echo "CPU units"
        nproc --all
        echo "Vote type"
        echo ${{ inputs.vote }}

    - name: Install solc
      shell: bash
      run: |
        set -e

        mkdir -p /home/runner/.solcx

        echo "Downloading solc..."
        curl -L "https://binaries.soliditylang.org/linux-amd64/solc-linux-amd64-v0.6.11+commit.5ef660b1" -o /home/runner/.solcx/solc-v0.8.28

        chmod +x /home/runner/.solcx/solc-v0.8.28

        echo "Checking solc version..."
        output="$( /home/runner/.solcx/solc-v0.8.28 --version )"
        echo "$output"

        expected="Version: 0.6.11+commit.5ef660b1"

        if [[ "$output" != *"$expected"* ]]; then
          echo "❌ solc version mismatch!"
          echo "Expected: $expected"
          echo "Got: $output"
          exit 1
        fi

        echo "✔ solc version is correct"


    - name: Run tests
      shell: bash
      run: >
        ${{ inputs.command }}
      env:
        ETHERSCAN_TOKEN: ${{ inputs.etherscan }}
        ETH_RPC_URL: ${{ inputs.rpc_url }}
