name: "Tests"
description: "Run brownie fork tests"

inputs:
  vote:
    description: "vote type: normal or large"
    required: false
    default: "normal"

runs:
  using: "composite"
  steps:
    # Tests from core repo
    - uses: actions/checkout@v4
      with:
        repository: lidofinance/core
        ref: develop
        path: core

    - name: Enable corepack
      shell: bash
      run: corepack enable

    - uses: actions/setup-node@v4
      with:
        node-version-file: ./core/.nvmrc
        cache: yarn

    - name: Install dependencies
      working-directory: core
      shell: bash
      run: yarn install --immutable
      env:
        CI: true

    - name: Compile contracts
      working-directory: core
      shell: bash
      run: yarn compile

    - name: Set env
      working-directory: core
      shell: bash
      run: cp .env.example .env

    - name: Run integration tests
      working-directory: core
      shell: bash
      run: yarn test:integration
      env:
        FORK_RPC_URL: http://host.docker.internal:8555
        LOG_LEVEL: info
