name: Normal vote CI Core Integration Tests

on:
  push:
    branches-ignore:
      - "master"
      - "feat/tests"
      - "feat/rc3"
      - "feat/rc2"
      - "feat/rc1"
      - "feat/next-vote"
  schedule:
    - cron: "0 0 * * TUE"
jobs:
  run-tests:
    name: Run all tests on NORMAL runner
    runs-on: "ubuntu-latest"
    timeout-minutes: 100

    services:
      hardhat-node:
        image: ghcr.io/lidofinance/hardhat-node:2.22.19.3-shanghai
        ports:
          - 8545:8545
        env:
          ETH_RPC_URL: "https://mainnet.infura.io/v3/${{ secrets.WEB3_INFURA_PROJECT_ID }}"

      hardhat-node-fork:
        image: ghcr.io/lidofinance/hardhat-node:2.22.19.3-shanghai
        ports:
          - 8555:8545
        env:
          ETH_RPC_URL: "http://hardhat-node:8545"

    steps:
      - uses: actions/checkout@v4

      - name: Check that the fork is ready
        shell: bash
        run: timeout 30 bash -c 'until printf "" 2>>/dev/null >>/dev/tcp/$0/$1; do sleep 1; done' 127.0.0.1 8545

      - name: Execute vote
        uses: ./.github/actions/execute_vote
        with:
          vote: "normal"
          infura: ${{ secrets.WEB3_INFURA_PROJECT_ID }}
          etherscan: ${{ secrets.ETHERSCAN_TOKEN }}

      - name: Checkout deployed-mainnet-upgrade.json
        uses: actions/checkout@v4
        with:
          repository: lidofinance/core
          path: lidofinance-core
          ref: feat/vaults
          sparse-checkout: true
          sparse-checkout-paths: |
            deployed-mainnet-upgrade.json

      - name: Pull Core Integration Tests Image
        run: docker pull ghcr.io/lidofinance/core-integration-tests:latest

      - name: Run Core Integration Tests
        run: |
          docker run \
            --env RPC_URL=http://host.docker.internal:8555 \
            --env NETWORK_STATE_FILE=deployed-mainnet-upgrade.json \
            --add-host=host.docker.internal:host-gateway \
            -v $(pwd)/lidofinance-core/deployed-mainnet-upgrade.json:/app/deployed-mainnet-upgrade.json \
            ghcr.io/lidofinance/core-integration-tests:latest
